
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package courseallocationsystem.analizadores;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int NAME_ED = 19;
  public static final int SALON = 5;
  public static final int SEMI = 15;
  public static final int QUOTE_MARK = 16;
  public static final int OPEN_ROUND_BRACKET = 12;
  public static final int HORARIO = 8;
  public static final int LITERAL = 17;
  public static final int ASIGNAR = 9;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int EDIFICIO = 4;
  public static final int USR_ESTUDIANTE = 11;
  public static final int error = 1;
  public static final int USUARIO = 2;
  public static final int ESTUDIANTE = 3;
  public static final int ENTERO = 18;
  public static final int CATEDRATICO = 6;
  public static final int CLOSE_ROUND_BRACKET = 13;
  public static final int CURSO = 7;
  public static final int USR_COLABORADOR = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "USUARIO",
  "ESTUDIANTE",
  "EDIFICIO",
  "SALON",
  "CATEDRATICO",
  "CURSO",
  "HORARIO",
  "ASIGNAR",
  "USR_COLABORADOR",
  "USR_ESTUDIANTE",
  "OPEN_ROUND_BRACKET",
  "CLOSE_ROUND_BRACKET",
  "COMMA",
  "SEMI",
  "QUOTE_MARK",
  "LITERAL",
  "ENTERO",
  "NAME_ED"
  };
}

